language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.13"
install:
  - python3 -m pip install -r djangotutorial/requirements.txt
before_script:
  - python3 djangotutorial/manage.py migrate
  - python3 djangotutorial/manage.py collectstatic --noinput
# only_create_app_version: "true"
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls djangotutorial/manage.py djangotutorial/test
after_script:
  - coveralls
before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "travisT"
  env: "travisT-env"
  bucket_name: ""
after_deploy: "echo 'DONE'"