language: python
python:
  - "3.12"
dist: focal
install:
  - python3 -m pip install -r djangotutorial/requirements.txt
before_script:
  - python3 djangotutorial/manage.py migrate
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls djangotutorial/manage.py test
after_script:
  - coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "djangoTutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-982534395285"
  skip_cleanup: true
  on:
    branch: main