language: python
python:
  - "3.12"
dist: focal
install:
  - python3 -m pip install -r djangotutorial/requirements.txt
before_script:
  - python3 djangotutorial/manage.py migrate
  # - python3 djangotutorial/manage.py collectstatic --noinput
# only_create_app_version: "true"
script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls djangotutorial/manage.py test
after_script:
  - coveralls
before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "djangoTutorial"
  env: "django-env"
  bucket: "elasticbeanstalk-us-east-1-982534395285"
  on:
    branch: main
after_deploy: "echo 'DONE'"